name: Full CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    

jobs:
  backend:
    uses: Wael569/GithubactionsPFE/.github/workflows/python.yml@main

      
  frontend:
    uses: Wael569/GithubactionsPFE/.github/workflows/node.yml@main

      
 

   
