name: Full CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    

jobs:

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: call Python file
        uses: Wael569/GithubactionsPFE/edit/main/.github/workflows/python.yml@main
      
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: call node file
        uses: Wael569/GithubactionsPFE/edit/main/.github/workflows/node.yml@main
